/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const set_panic_hook: () => void;
export const __wbg_wasmimageprocessor_free: (a: number, b: number) => void;
export const wasmimageprocessor_new: (a: number, b: number) => [number, number, number];
export const wasmimageprocessor_getWidth: (a: number) => number;
export const wasmimageprocessor_getHeight: (a: number) => number;
export const wasmimageprocessor_scaleExact: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const wasmimageprocessor_scaleToWidth: (a: number, b: number, c: number, d: number) => [number, number];
export const wasmimageprocessor_scaleToHeight: (a: number, b: number, c: number, d: number) => [number, number];
export const wasmimageprocessor_scaleByFactor: (a: number, b: number, c: number, d: number) => [number, number];
export const wasmimageprocessor_crop: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const wasmimageprocessor_cropFromCenter: (a: number, b: number, c: number) => [number, number];
export const wasmimageprocessor_cropToAspectRatio: (a: number, b: number, c: number) => [number, number];
export const wasmimageprocessor_rotate: (a: number, b: number) => [number, number];
export const wasmimageprocessor_rotate90: (a: number) => [number, number];
export const wasmimageprocessor_rotate180: (a: number) => [number, number];
export const wasmimageprocessor_rotate270: (a: number) => [number, number];
export const wasmimageprocessor_flipHorizontal: (a: number) => [number, number];
export const wasmimageprocessor_flipVertical: (a: number) => [number, number];
export const wasmimageprocessor_toFormat: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmimageprocessor_toFormatWithQuality: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const wasmimageprocessor_toPng: (a: number) => [number, number, number, number];
export const wasmimageprocessor_toJpeg: (a: number) => [number, number, number, number];
export const wasmimageprocessor_toJpegWithQuality: (a: number, b: number) => [number, number, number, number];
export const wasmimageprocessor_toWebp: (a: number) => [number, number, number, number];
export const wasmimageprocessor_createPreview: (a: number, b: number) => [number, number, number, number];
export const wasmimageprocessor_exportDual: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number) => [number, number, number];
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
